name: datn
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6

  connectivity_plus: ^6.0.3
  fluttertoast: ^8.2.5
  flutter_screenutil: ^5.9.0
  intl: ^0.19.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  timezone: ^0.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins_light_300.ttf
          weight: 300
        - asset: assets/font/poppins_regular_400.ttf
          weight: 400
        - asset: assets/font/poppins_medium_500.ttf
          weight: 500
        - asset: assets/font/poppins_semi_bold_600.ttf
          weight: 600
        - asset: assets/font/poppins_bold_700.ttf
          weight: 700